version: "3"
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: cdr
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: cdr
      POSTGRES_HOST: cdr.c5fxgej1iixe.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: arn:aws:s3:::udacity-794501321189-dev
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: cdr
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: cdr
      POSTGRES_HOST: cdr.c5fxgej1iixe.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: arn:aws:s3:::udacity-794501321189-dev
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend
    ports:
      - "8101:80"
