org: zunguciii
app: aws-node-project
service: aws-node-project

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
