language: node_js
node_js:
  - 14
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./Part3/udagram-api-feed
  - docker build -t udagram-api-user ./Part3/udagram-api-user
  - docker build -t udagram-frontend ./Part3/udagram-frontend
  - docker build -t reverseproxy ./Part3/udagram-reverseproxy
  #tagging
  - docker tag udagram-api-feed zunguciii/udagram-api-feed:v1
  - docker tag udagram-api-user zunguciii/udagram-api-user:v1
  - docker tag udagram-frontend zunguciii/udagram-frontend:v1
  - docker tag reverseproxy zunguciii/reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zunguciii/udagram-api-feed:v1
  - docker push zunguciii/udagram-api-user:v1
  - docker push zunguciii/udagram-frontend:v1
  - docker push zunguciii/reverseproxy:v1
